<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\DatabaseMigrations;


/**
 * @property  thread
 */

class ThreadTest extends TestCase
{
    protected $thread;
    use DatabaseMigrations;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        factory('App\Thread')->create();
        $this->thread= factory('App\Thread')->create();

    }

    /** @test  */

    function a_thread_has_replies(){

         $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection',$this->thread->replies);
    }


    /** @test  */

    function a_thread_has_creator(){

        $this->assertInstanceOf('App\User',$this->thread->creator);
    }
    /** @test  */

    function a_thread_can_add_a_reply(){


        $this->thread->addreply([
            'body'=>'balalaw',
            'user_id'=>1
        ]);

        $this->assertCount(1,$this->thread->replies);
    }
}
